spring:
  cloud:
    gateway:
      routes:
#生产路由
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#用户
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#库存
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#        第三方
        - id: third_party
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}


#        nginx
        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=yzhmall.com,item.yzhmall.com

#        查询
        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.yzhmall.com
#        权限
        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.yzhmall.com
#        购物车
        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.yzhmall.com
#        订单
        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.yzhmall.com

        #        秒杀
        - id: mall_seckill_route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.yzhmall.com