spring:
  cloud:
    gateway:
      routes:
#生产路由
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#用户
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#库存
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#        第三方
        - id: third_party
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}


#        第三方
        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=**.yzhmall.com

