spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.22.129:3306/mall_sms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8005