server:
  port: 8007
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.22.129:3306/mall_wms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-ware
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml