spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: third-party
  alicloud:
    sms:
      host: https://feginesms.market.alicloudapi.com
      path: /codeNotice
      appcode: 175feb298ae640cd990510697cee7138
      skin: 1
      sign: 1